/* Automaattisesti generoitu tiedostosta training-content/v1. Älä muokkaa käsin. */
export const trainingContentV1 = {
  release: {
    releaseId: 'adult-resistance-v1.0.0',
    version: '1.0.0',
    publishedAt: '2026-08-25T12:00:00.000Z',
    status: 'INTERNAL_BETA',
    immutable: true,
    minimumAge: 18,
    supportedSessionKinds: ['STRENGTH'],
    unsupportedSessionKinds: ['SPEED_POWER', 'SPORT', 'MATCH'],
    schemaVersions: {
      sources: 1,
      claims: 1,
      rules: 1,
      exercises: 1,
      substitutions: 1,
    },
    contentDigest: '5e4e72efd00a8503bf2faf85cef9d93ae8906ab95d4f475a7365111764fd1c8a',
  },
  sources: [
    {
      id: 'ACSM-RT-2026',
      type: 'POSITION_STAND',
      title:
        'American College of Sports Medicine Position Stand. Resistance Training Prescription for Muscle Function, Hypertrophy, and Physical Performance in Healthy Adults',
      year: 2026,
      pmid: '41843416',
      organization: 'American College of Sports Medicine',
      status: 'ACTIVE',
    },
    {
      id: 'CURRIER-RT-NMA-2023',
      type: 'META_ANALYSIS',
      title:
        'Resistance training prescription for muscle strength and hypertrophy in healthy adults: a systematic review and Bayesian network meta-analysis',
      authors: ['Currier BS', 'McLeod JC', 'Banfield L'],
      year: 2023,
      pmid: '37414459',
      status: 'ACTIVE',
    },
    {
      id: 'GRGIC-FAILURE-2021',
      type: 'SYSTEMATIC_REVIEW',
      title:
        'Effects of resistance training performed to repetition failure or non-failure on muscular strength and hypertrophy: a systematic review and meta-analysis',
      authors: ['Grgic J', 'Schoenfeld BJ', 'Orazem J', 'Sabol F'],
      year: 2021,
      pmid: '33497853',
      status: 'ACTIVE',
    },
    {
      id: 'BASTOS-RIR-2024',
      type: 'SYSTEMATIC_REVIEW',
      title: 'Repetitions in reserve scale in resistance training: a scoping review',
      authors: ['Bastos ESM', 'de Souza EO'],
      year: 2024,
      pmid: '38563729',
      status: 'ACTIVE',
    },
    {
      id: 'LOPEZ-LOAD-2021',
      type: 'META_ANALYSIS',
      title:
        'Resistance Training Load Effects on Muscle Hypertrophy and Strength Gain: Systematic Review and Network Meta-analysis',
      authors: ['Lopez P', 'Radaelli R', 'Taaffe DR'],
      year: 2021,
      doi: '10.1249/MSS.0000000000002585',
      pmid: '33433148',
      status: 'ACTIVE',
    },
    {
      id: 'PELLAND-DOSE-2026',
      type: 'META_ANALYSIS',
      title:
        'Resistance training dose-response effects on strength and hypertrophy in healthy adults',
      authors: ['Pelland JC'],
      year: 2026,
      pmid: '41343037',
      status: 'ACTIVE',
    },
    {
      id: 'ALIZADEH-ROM-2023',
      type: 'SYSTEMATIC_REVIEW',
      title:
        'Resistance Training Induces Improvements in Range of Motion: A Systematic Review and Meta-Analysis',
      authors: ['Alizadeh S'],
      year: 2023,
      pmid: '36622555',
      status: 'ACTIVE',
    },
    {
      id: 'WHO-PA-2020',
      type: 'CONSENSUS',
      title: 'WHO Guidelines on Physical Activity and Sedentary Behaviour',
      year: 2020,
      organization: 'World Health Organization',
      status: 'ACTIVE',
    },
    {
      id: 'SCHUMANN-CONCURRENT-2022',
      type: 'META_ANALYSIS',
      title:
        'Compatibility of Concurrent Aerobic and Strength Training for Skeletal Muscle Size and Function: An Updated Systematic Review and Meta-Analysis',
      authors: ['Schumann M', 'Feito Y', 'Figueiredo C'],
      year: 2022,
      pmid: '34757594',
      status: 'ACTIVE',
    },
    {
      id: 'NSCA-YOUTH-2009',
      type: 'POSITION_STAND',
      title:
        'Youth resistance training: updated position statement paper from the National Strength and Conditioning Association',
      year: 2009,
      pmid: '19620931',
      organization: 'National Strength and Conditioning Association',
      status: 'ACTIVE',
    },
    {
      id: 'OLIVER-YOUTH-TEAM-SPORT-2024',
      type: 'META_ANALYSIS',
      title:
        'The Effects of Strength, Plyometric and Combined Training on Strength, Power and Speed Characteristics in High-Level, Highly Trained Male Youth Soccer Players',
      authors: ['Oliver JL'],
      year: 2024,
      pmid: '37897637',
      status: 'ACTIVE',
    },
    {
      id: 'LUO-FEMALE-YOUTH-2025',
      type: 'META_ANALYSIS',
      title:
        'Effects of Strength and Plyometric Training on Vertical Jump, Linear Sprint, and Change-of-Direction Speed in Female Adolescent Team Sport Athletes',
      authors: ['Luo S'],
      year: 2025,
      pmid: '40469857',
      status: 'ACTIVE',
    },
    {
      id: 'DAEHLIN-HOCKEY-2017',
      type: 'RANDOMIZED_TRIAL',
      title:
        "Improvement of Ice Hockey Players' On-Ice Sprint With Combined Plyometric and Strength Training",
      authors: ['Dæhlin TE'],
      year: 2017,
      pmid: '27918670',
      status: 'ACTIVE',
    },
    {
      id: 'DIETZE-HERMOSA-HOCKEY-2024',
      type: 'RANDOMIZED_TRIAL',
      title:
        'The Impact of an 8-Week Resisted Sprint Training Program on Ice Skating Performance in Male Youth Ice Hockey Players',
      authors: ['Dietze-Hermosa MS'],
      year: 2024,
      pmid: '38620058',
      status: 'ACTIVE',
    },
    {
      id: 'AKERLUND-FLOORBALL-2020',
      type: 'RANDOMIZED_TRIAL',
      title:
        'Forty-five per cent lower acute injury incidence but no effect on overuse injury prevalence in youth floorball players who used an injury prevention exercise programme',
      authors: ['Åkerlund I'],
      year: 2020,
      pmid: '31992545',
      status: 'ACTIVE',
    },
    {
      id: 'FIFA11-COLLEGIATE-2015',
      type: 'RANDOMIZED_TRIAL',
      title: 'The FIFA 11+ injury prevention program in collegiate football',
      year: 2015,
      pmid: '26378030',
      status: 'ACTIVE',
    },
    {
      id: 'NORDIC-HAMSTRING-2017',
      type: 'META_ANALYSIS',
      title:
        'Effect of Injury Prevention Programs that Include the Nordic Hamstring Exercise on Hamstring Injury Rates in Soccer Players',
      year: 2017,
      pmid: '27752982',
      status: 'ACTIVE',
    },
    {
      id: 'STOJANOVIC-PLYOMETRIC-2017',
      type: 'META_ANALYSIS',
      title:
        'Effect of Plyometric Training on Vertical Jump Performance in Female Athletes',
      authors: ['Stojanović E'],
      year: 2017,
      pmid: '27704484',
      status: 'ACTIVE',
    },
  ],
  claims: [
    {
      id: 'CLAIM-ADULT-RT-BASE-001',
      population: {
        minimumAge: 18,
        trainingStatus: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'],
        healthStatus: ['HEALTHY'],
      },
      intervention: 'Progressive resistance training using major movement patterns',
      outcomes: ['muscle strength', 'muscle hypertrophy', 'physical function'],
      context: ['healthy adults', 'supervised or self-directed resistance training'],
      doseEnvelope: {
        sessionsPerWeek: [1, 4],
        setsPerExercise: [1, 5],
        repetitions: [3, 15],
        targetRir: [1, 5],
        durationMinutes: [20, 90],
      },
      certainty: 'HIGH',
      directness: 'DIRECT',
      recommendationStrength: 'STRONG',
      sourceIds: ['ACSM-RT-2026', 'CURRIER-RT-NMA-2023', 'PELLAND-DOSE-2026'],
      technicalValidation: 'PASSED',
      scientificReview: 'PENDING_HUMAN_REVIEW',
      reviewedBy: [],
      status: 'PUBLISHED_INTERNAL',
      version: '1.0.0',
    },
    {
      id: 'CLAIM-ADULT-RT-EFFORT-001',
      population: {
        minimumAge: 18,
        trainingStatus: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'],
        healthStatus: ['HEALTHY'],
      },
      intervention:
        'Resistance training with repetitions in reserve and without routine momentary failure',
      comparator: 'Routine training to momentary muscular failure',
      outcomes: ['strength', 'hypertrophy', 'fatigue management'],
      context: ['healthy adults'],
      doseEnvelope: {
        targetRir: [1, 5],
      },
      certainty: 'MODERATE',
      directness: 'DIRECT',
      recommendationStrength: 'CONDITIONAL',
      sourceIds: ['GRGIC-FAILURE-2021', 'BASTOS-RIR-2024', 'ACSM-RT-2026'],
      technicalValidation: 'PASSED',
      scientificReview: 'PENDING_HUMAN_REVIEW',
      reviewedBy: [],
      status: 'PUBLISHED_INTERNAL',
      version: '1.0.0',
    },
    {
      id: 'CLAIM-ADULT-RT-LOAD-001',
      population: {
        minimumAge: 18,
        trainingStatus: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'],
        healthStatus: ['HEALTHY'],
      },
      intervention: 'Resistance training across low, moderate, and high load ranges',
      outcomes: ['muscle strength', 'muscle hypertrophy'],
      context: ['healthy adults'],
      doseEnvelope: {
        repetitions: [3, 15],
        percent1Rm: [40, 90],
      },
      certainty: 'MODERATE',
      directness: 'DIRECT',
      recommendationStrength: 'CONDITIONAL',
      sourceIds: ['LOPEZ-LOAD-2021', 'CURRIER-RT-NMA-2023'],
      technicalValidation: 'PASSED',
      scientificReview: 'PENDING_HUMAN_REVIEW',
      reviewedBy: [],
      status: 'PUBLISHED_INTERNAL',
      version: '1.0.0',
    },
    {
      id: 'CLAIM-ADULT-RT-ROM-001',
      population: {
        minimumAge: 18,
        healthStatus: ['HEALTHY'],
      },
      intervention: 'Resistance training through a controlled available range of motion',
      outcomes: ['range of motion', 'strength'],
      context: ['healthy adults'],
      certainty: 'MODERATE',
      directness: 'DIRECT',
      recommendationStrength: 'CONDITIONAL',
      sourceIds: ['ALIZADEH-ROM-2023'],
      technicalValidation: 'PASSED',
      scientificReview: 'PENDING_HUMAN_REVIEW',
      reviewedBy: [],
      status: 'PUBLISHED_INTERNAL',
      version: '1.0.0',
    },
    {
      id: 'CLAIM-ADULT-PA-BASE-001',
      population: {
        minimumAge: 18,
        healthStatus: ['HEALTHY'],
      },
      intervention: 'Regular aerobic and muscle-strengthening physical activity',
      outcomes: ['health', 'physical function'],
      context: ['population-level guidance'],
      certainty: 'HIGH',
      directness: 'ADJACENT',
      recommendationStrength: 'STRONG',
      sourceIds: ['WHO-PA-2020'],
      technicalValidation: 'PASSED',
      scientificReview: 'PENDING_HUMAN_REVIEW',
      reviewedBy: [],
      status: 'PUBLISHED_INTERNAL',
      version: '1.0.0',
    },
    {
      id: 'CLAIM-ADULT-CONCURRENT-001',
      population: {
        minimumAge: 18,
        healthStatus: ['HEALTHY'],
      },
      intervention: 'Concurrent aerobic and resistance training',
      outcomes: ['strength', 'hypertrophy', 'explosive strength'],
      context: ['weekly schedule design'],
      certainty: 'MODERATE',
      directness: 'ADJACENT',
      recommendationStrength: 'CONDITIONAL',
      sourceIds: ['SCHUMANN-CONCURRENT-2022'],
      technicalValidation: 'PASSED',
      scientificReview: 'PENDING_HUMAN_REVIEW',
      reviewedBy: [],
      status: 'PUBLISHED_INTERNAL',
      version: '1.0.0',
    },
    {
      id: 'CLAIM-YOUTH-TEAM-SPORT-DRAFT-001',
      population: {
        minimumAge: 12,
        maximumAge: 17,
        healthStatus: ['HEALTHY'],
        sportCodes: ['football', 'ice-hockey', 'floorball', 'volleyball'],
      },
      intervention:
        'Supervised youth resistance, plyometric, and injury-prevention training',
      outcomes: ['strength', 'power', 'speed', 'injury incidence'],
      context: ['youth team sports', 'future architecture only'],
      certainty: 'LOW',
      directness: 'INDIRECT',
      recommendationStrength: 'CONDITIONAL',
      sourceIds: [
        'NSCA-YOUTH-2009',
        'OLIVER-YOUTH-TEAM-SPORT-2024',
        'LUO-FEMALE-YOUTH-2025',
        'AKERLUND-FLOORBALL-2020',
        'FIFA11-COLLEGIATE-2015',
        'NORDIC-HAMSTRING-2017',
        'STOJANOVIC-PLYOMETRIC-2017',
      ],
      technicalValidation: 'PASSED',
      scientificReview: 'PENDING_HUMAN_REVIEW',
      reviewedBy: [],
      status: 'DRAFT',
      version: '0.1.0',
    },
    {
      id: 'CLAIM-ICE-HOCKEY-DRAFT-001',
      population: {
        minimumAge: 12,
        sportCodes: ['ice-hockey'],
      },
      intervention: 'Strength, plyometric, and resisted sprint training for ice hockey',
      outcomes: ['on-ice sprint', 'power'],
      context: ['future sport module only'],
      certainty: 'LOW',
      directness: 'INDIRECT',
      recommendationStrength: 'CONDITIONAL',
      sourceIds: ['DAEHLIN-HOCKEY-2017', 'DIETZE-HERMOSA-HOCKEY-2024'],
      technicalValidation: 'PASSED',
      scientificReview: 'PENDING_HUMAN_REVIEW',
      reviewedBy: [],
      status: 'DRAFT',
      version: '0.1.0',
    },
  ],
  rules: [
    {
      id: 'ADULT-ONLY-001',
      version: '1.0.0',
      claimIds: ['CLAIM-ADULT-RT-BASE-001'],
      populationPredicate: 'age >= 18 && healthStatus == HEALTHY',
      goalPredicate: 'sessionKind == STRENGTH',
      action: 'Allow the adult resistance prescription pipeline.',
      safetyClass: 'PROCEED',
      policyBasis: 'PRODUCT_POLICY',
      status: 'PUBLISHED',
    },
    {
      id: 'RT-BASE-DOSE-001',
      version: '1.0.0',
      claimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-LOAD-001'],
      populationPredicate: 'age >= 18 && healthStatus == HEALTHY',
      goalPredicate:
        'goal in [GENERAL_FITNESS, MAX_STRENGTH, MUSCLE_GAIN, BODY_RECOMPOSITION]',
      action:
        'Select goal- and experience-specific sets, repetitions, and rest inside the published dose envelope.',
      safetyClass: 'PROCEED',
      policyBasis: 'EVIDENCE',
      status: 'PUBLISHED',
    },
    {
      id: 'RT-RIR-001',
      version: '1.0.0',
      claimIds: ['CLAIM-ADULT-RT-EFFORT-001'],
      populationPredicate: 'age >= 18 && healthStatus == HEALTHY',
      goalPredicate: 'sessionKind == STRENGTH',
      action:
        'Prescribe a conservative repetitions-in-reserve range and record completed-set RIR.',
      safetyClass: 'PROCEED',
      policyBasis: 'EVIDENCE',
      status: 'PUBLISHED',
    },
    {
      id: 'RT-NO-FAILURE-001',
      version: '1.0.0',
      claimIds: ['CLAIM-ADULT-RT-EFFORT-001'],
      populationPredicate: 'age >= 18',
      goalPredicate: 'sessionKind == STRENGTH',
      action: 'Do not prescribe routine momentary muscular failure.',
      safetyClass: 'MODIFY',
      policyBasis: 'PRODUCT_POLICY',
      status: 'PUBLISHED',
    },
    {
      id: 'RT-CALIBRATION-001',
      version: '1.0.0',
      claimIds: ['CLAIM-ADULT-RT-EFFORT-001', 'CLAIM-ADULT-RT-LOAD-001'],
      populationPredicate: 'comparableSetCount < 2',
      goalPredicate: 'sessionKind == STRENGTH',
      action:
        'Use a conservative calibration set without a precise kilogram prescription.',
      safetyClass: 'MODIFY',
      policyBasis: 'PRODUCT_POLICY',
      status: 'PUBLISHED',
    },
    {
      id: 'RT-PROGRESSION-001',
      version: '1.0.0',
      claimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-EFFORT-001'],
      populationPredicate: 'comparableSuccessfulSessions >= 2 && pain == NONE',
      goalPredicate: 'sessionKind == STRENGTH',
      action:
        'Change only one primary prescription variable. Use one available load increment; allow a smallest-available-increment exception above five percent only after two pain-free, technically sound sessions in the target RIR range.',
      safetyClass: 'MODIFY',
      policyBasis: 'PRODUCT_POLICY',
      status: 'PUBLISHED',
    },
  ],
  exercises: [
    {
      id: 'exercise-chair-squat-v1',
      code: 'CHAIR_SQUAT',
      version: '1.0.0',
      nameFi: 'Tuolilta ylösnousu',
      method: 'RESISTANCE',
      movementPatterns: ['SQUAT'],
      primaryMuscles: ['quadriceps', 'gluteals'],
      secondaryMuscles: ['trunk'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 1,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 1,
        local: 2,
        neural: 1,
        eccentric: 1,
        sorenessRisk: 1,
      },
      contraindicationTags: ['ACUTE_KNEE_PAIN', 'GAIT_ALTERING_PAIN'],
      prerequisiteTags: [],
      regressionCodes: [],
      progressionCodes: ['BODYWEIGHT_SQUAT', 'GOBLET_SQUAT'],
      substitutionCodes: ['BODYWEIGHT_SQUAT', 'LEG_PRESS'],
      adaptationTargets: ['GENERAL_STRENGTH', 'LOWER_BODY_STRENGTH', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-ROM-001'],
      instructionsFi: [
        'Asetu tukevan tuolin eteen.',
        'Nouse hallitusti seisomaan ja laskeudu rauhallisesti takaisin.',
        'Pidä polvet varpaiden suuntaisina ja käytä kivutonta liikerataa.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-bodyweight-squat-v1',
      code: 'BODYWEIGHT_SQUAT',
      version: '1.0.0',
      nameFi: 'Kehonpainokyykky',
      method: 'RESISTANCE',
      movementPatterns: ['SQUAT'],
      primaryMuscles: ['quadriceps', 'gluteals'],
      secondaryMuscles: ['trunk'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 2,
        local: 2,
        neural: 1,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_KNEE_PAIN', 'GAIT_ALTERING_PAIN'],
      prerequisiteTags: ['CONTROLLED_SQUAT'],
      regressionCodes: ['CHAIR_SQUAT'],
      progressionCodes: ['GOBLET_SQUAT'],
      substitutionCodes: ['CHAIR_SQUAT', 'GOBLET_SQUAT'],
      adaptationTargets: ['GENERAL_STRENGTH', 'LOWER_BODY_STRENGTH'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-ROM-001'],
      instructionsFi: [
        'Seiso tukevassa asennossa.',
        'Vie lantiota alas ja taakse hallitusti.',
        'Nouse ylös pitäen polvet varpaiden suuntaisina.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-goblet-squat-v1',
      code: 'GOBLET_SQUAT',
      version: '1.0.0',
      nameFi: 'Maljakyykky',
      method: 'RESISTANCE',
      movementPatterns: ['SQUAT'],
      primaryMuscles: ['quadriceps', 'gluteals'],
      secondaryMuscles: ['trunk', 'upper back'],
      equipment: ['Käsipainot', 'Kahvakuula'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['DUMBBELL_KG_EACH', 'EXTERNAL_KG'],
      fatigue: {
        systemic: 3,
        local: 3,
        neural: 2,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_KNEE_PAIN', 'GAIT_ALTERING_PAIN'],
      prerequisiteTags: ['CONTROLLED_SQUAT'],
      regressionCodes: ['BODYWEIGHT_SQUAT', 'CHAIR_SQUAT'],
      progressionCodes: ['LEG_PRESS'],
      substitutionCodes: ['BODYWEIGHT_SQUAT', 'LEG_PRESS'],
      adaptationTargets: ['GENERAL_STRENGTH', 'LOWER_BODY_STRENGTH', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-LOAD-001'],
      instructionsFi: [
        'Pidä paino vakaasti rinnan edessä.',
        'Kyykkää hallitulla ja kivuttomalla liikeradalla.',
        'Nouse ilman polvien painumista sisään.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-leg-press-v1',
      code: 'LEG_PRESS',
      version: '1.0.0',
      nameFi: 'Jalkaprässi',
      method: 'RESISTANCE',
      movementPatterns: ['SQUAT'],
      primaryMuscles: ['quadriceps', 'gluteals'],
      secondaryMuscles: ['hamstrings'],
      equipment: ['Kuntosalilaitteet'],
      environments: ['GYM'],
      unilateral: false,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['MACHINE_KG'],
      fatigue: {
        systemic: 3,
        local: 4,
        neural: 2,
        eccentric: 3,
        sorenessRisk: 3,
      },
      contraindicationTags: ['ACUTE_KNEE_PAIN', 'GAIT_ALTERING_PAIN'],
      prerequisiteTags: ['MACHINE_SETUP'],
      regressionCodes: ['CHAIR_SQUAT', 'GOBLET_SQUAT'],
      progressionCodes: [],
      substitutionCodes: ['GOBLET_SQUAT', 'CHAIR_SQUAT'],
      adaptationTargets: ['LOWER_BODY_STRENGTH', 'HYPERTROPHY', 'MAX_STRENGTH'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-LOAD-001'],
      instructionsFi: [
        'Säädä istuin niin, että alaselkä pysyy tuettuna.',
        'Laske kelkka hallitusti kivuttomalle syvyydelle.',
        'Työnnä jalkapohjilla ilman polvien lukitsemista.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-glute-bridge-v1',
      code: 'GLUTE_BRIDGE',
      version: '1.0.0',
      nameFi: 'Lantionnosto',
      method: 'RESISTANCE',
      movementPatterns: ['HINGE'],
      primaryMuscles: ['gluteals'],
      secondaryMuscles: ['hamstrings', 'trunk'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 1,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 1,
        local: 2,
        neural: 1,
        eccentric: 1,
        sorenessRisk: 1,
      },
      contraindicationTags: ['ACUTE_BACK_PAIN'],
      prerequisiteTags: [],
      regressionCodes: [],
      progressionCodes: ['DUMBBELL_RDL', 'CABLE_PULL_THROUGH'],
      substitutionCodes: ['DUMBBELL_RDL', 'CABLE_PULL_THROUGH'],
      adaptationTargets: ['GENERAL_STRENGTH', 'HIP_EXTENSION', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Aseta jalat tukevasti lattialle.',
        'Nosta lantio puristamalla pakaroita.',
        'Lopeta liike ennen alaselän yliojennusta.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-dumbbell-rdl-v1',
      code: 'DUMBBELL_RDL',
      version: '1.0.0',
      nameFi: 'Romanialainen maastaveto käsipainoilla',
      method: 'RESISTANCE',
      movementPatterns: ['HINGE'],
      primaryMuscles: ['hamstrings', 'gluteals'],
      secondaryMuscles: ['back extensors', 'grip'],
      equipment: ['Käsipainot'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 3,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['DUMBBELL_KG_EACH'],
      fatigue: {
        systemic: 3,
        local: 3,
        neural: 2,
        eccentric: 4,
        sorenessRisk: 3,
      },
      contraindicationTags: ['ACUTE_BACK_PAIN', 'HAMSTRING_INJURY'],
      prerequisiteTags: ['CONTROLLED_HINGE'],
      regressionCodes: ['GLUTE_BRIDGE'],
      progressionCodes: ['BARBELL_RDL'],
      substitutionCodes: ['GLUTE_BRIDGE', 'BARBELL_RDL'],
      adaptationTargets: ['GENERAL_STRENGTH', 'HIP_EXTENSION', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-LOAD-001'],
      instructionsFi: [
        'Pidä painot lähellä vartaloa.',
        'Vie lantiota taakse selän asennon säilyessä vakaana.',
        'Nouse pakaroiden ja takareisien työllä ilman nykäisyä.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-barbell-rdl-v1',
      code: 'BARBELL_RDL',
      version: '1.0.0',
      nameFi: 'Romanialainen maastaveto levytangolla',
      method: 'RESISTANCE',
      movementPatterns: ['HINGE'],
      primaryMuscles: ['hamstrings', 'gluteals'],
      secondaryMuscles: ['back extensors', 'grip'],
      equipment: ['Levytanko ja painot'],
      environments: ['GYM'],
      unilateral: false,
      technicalComplexity: 4,
      minimumExperience: 'INTERMEDIATE',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['EXTERNAL_KG'],
      fatigue: {
        systemic: 4,
        local: 4,
        neural: 4,
        eccentric: 4,
        sorenessRisk: 4,
      },
      contraindicationTags: ['ACUTE_BACK_PAIN', 'HAMSTRING_INJURY'],
      prerequisiteTags: ['CONTROLLED_HINGE', 'BARBELL_SETUP'],
      regressionCodes: ['DUMBBELL_RDL', 'GLUTE_BRIDGE'],
      progressionCodes: [],
      substitutionCodes: ['DUMBBELL_RDL', 'CABLE_PULL_THROUGH'],
      adaptationTargets: ['MAX_STRENGTH', 'HIP_EXTENSION', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-LOAD-001'],
      instructionsFi: [
        'Ota tasainen ote tangosta ja pidä se lähellä reisiä.',
        'Vie lantiota taakse hallitusti.',
        'Lopeta liikerata, kun selän neutraali asento ei enää säily.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-cable-pull-through-v1',
      code: 'CABLE_PULL_THROUGH',
      version: '1.0.0',
      nameFi: 'Taljaveto jalkojen välistä',
      method: 'RESISTANCE',
      movementPatterns: ['HINGE'],
      primaryMuscles: ['gluteals', 'hamstrings'],
      secondaryMuscles: ['trunk'],
      equipment: ['Kuntosalilaitteet'],
      environments: ['GYM'],
      unilateral: false,
      technicalComplexity: 3,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['MACHINE_KG'],
      fatigue: {
        systemic: 2,
        local: 3,
        neural: 2,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_BACK_PAIN'],
      prerequisiteTags: ['CONTROLLED_HINGE', 'MACHINE_SETUP'],
      regressionCodes: ['GLUTE_BRIDGE'],
      progressionCodes: ['DUMBBELL_RDL'],
      substitutionCodes: ['GLUTE_BRIDGE', 'DUMBBELL_RDL'],
      adaptationTargets: ['HIP_EXTENSION', 'HYPERTROPHY', 'GENERAL_STRENGTH'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Asetu selkä taljaan päin ja pidä köysi jalkojen välissä.',
        'Vie lantiota taakse hallitusti.',
        'Ojenna lantio ilman alaselän yliojennusta.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-supported-split-squat-v1',
      code: 'SUPPORTED_SPLIT_SQUAT',
      version: '1.0.0',
      nameFi: 'Tuettu askelkyykky paikallaan',
      method: 'RESISTANCE',
      movementPatterns: ['SINGLE_LEG', 'SQUAT'],
      primaryMuscles: ['quadriceps', 'gluteals'],
      secondaryMuscles: ['calves', 'trunk'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: true,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 2,
        local: 3,
        neural: 2,
        eccentric: 3,
        sorenessRisk: 3,
      },
      contraindicationTags: [
        'ACUTE_KNEE_PAIN',
        'BALANCE_LIMITATION',
        'GAIT_ALTERING_PAIN',
      ],
      prerequisiteTags: ['SUPPORTED_STANCE'],
      regressionCodes: ['CHAIR_SQUAT'],
      progressionCodes: ['REVERSE_LUNGE', 'STEP_UP'],
      substitutionCodes: ['STEP_UP', 'REVERSE_LUNGE'],
      adaptationTargets: ['LOWER_BODY_STRENGTH', 'SINGLE_LEG_CONTROL', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Ota tukea vakaasta pinnasta.',
        'Laskeudu suoraan alaspäin hallitusti.',
        'Ponnista etummaisen jalan kautta takaisin ylös.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-reverse-lunge-v1',
      code: 'REVERSE_LUNGE',
      version: '1.0.0',
      nameFi: 'Taakseaskelkyykky',
      method: 'RESISTANCE',
      movementPatterns: ['SINGLE_LEG', 'SQUAT'],
      primaryMuscles: ['quadriceps', 'gluteals'],
      secondaryMuscles: ['calves', 'trunk'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: true,
      technicalComplexity: 3,
      minimumExperience: 'INTERMEDIATE',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 3,
        local: 3,
        neural: 2,
        eccentric: 3,
        sorenessRisk: 3,
      },
      contraindicationTags: [
        'ACUTE_KNEE_PAIN',
        'BALANCE_LIMITATION',
        'GAIT_ALTERING_PAIN',
      ],
      prerequisiteTags: ['SINGLE_LEG_CONTROL'],
      regressionCodes: ['SUPPORTED_SPLIT_SQUAT'],
      progressionCodes: [],
      substitutionCodes: ['SUPPORTED_SPLIT_SQUAT', 'STEP_UP'],
      adaptationTargets: ['LOWER_BODY_STRENGTH', 'SINGLE_LEG_CONTROL', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Astu yhdellä jalalla taakse.',
        'Laskeudu hallitusti etummaisen polven seuratessa varpaiden suuntaa.',
        'Palaa alkuun etummaisen jalan voimalla.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-step-up-v1',
      code: 'STEP_UP',
      version: '1.0.0',
      nameFi: 'Nousu matalalle korokkeelle',
      method: 'RESISTANCE',
      movementPatterns: ['SINGLE_LEG'],
      primaryMuscles: ['quadriceps', 'gluteals'],
      secondaryMuscles: ['calves', 'trunk'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: true,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 2,
        local: 3,
        neural: 2,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: [
        'ACUTE_KNEE_PAIN',
        'BALANCE_LIMITATION',
        'GAIT_ALTERING_PAIN',
      ],
      prerequisiteTags: ['STABLE_STEP'],
      regressionCodes: ['CHAIR_SQUAT'],
      progressionCodes: ['REVERSE_LUNGE'],
      substitutionCodes: ['SUPPORTED_SPLIT_SQUAT', 'REVERSE_LUNGE'],
      adaptationTargets: ['LOWER_BODY_STRENGTH', 'SINGLE_LEG_CONTROL', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Käytä vakaata, matalaa koroketta.',
        'Nouse korokkeelle etummaisen jalan voimalla.',
        'Laskeudu hitaasti takaisin hallintaan.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-elevated-push-up-v1',
      code: 'ELEVATED_PUSH_UP',
      version: '1.0.0',
      nameFi: 'Korotettu punnerrus',
      method: 'RESISTANCE',
      movementPatterns: ['HORIZONTAL_PUSH'],
      primaryMuscles: ['chest', 'triceps'],
      secondaryMuscles: ['shoulders', 'trunk'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 1,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 1,
        local: 2,
        neural: 1,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'ACUTE_WRIST_PAIN'],
      prerequisiteTags: [],
      regressionCodes: [],
      progressionCodes: ['PUSH_UP', 'DUMBBELL_BENCH_PRESS'],
      substitutionCodes: ['PUSH_UP', 'DUMBBELL_BENCH_PRESS'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'HORIZONTAL_PUSH', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Aseta kädet vakaalle korokkeelle.',
        'Pidä vartalo suorana kantapäistä päähän.',
        'Laske rintakehä hallitusti ja työnnä takaisin ilman kipua.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-push-up-v1',
      code: 'PUSH_UP',
      version: '1.0.0',
      nameFi: 'Punnerrus',
      method: 'RESISTANCE',
      movementPatterns: ['HORIZONTAL_PUSH'],
      primaryMuscles: ['chest', 'triceps'],
      secondaryMuscles: ['shoulders', 'trunk'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 3,
      minimumExperience: 'INTERMEDIATE',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 2,
        local: 3,
        neural: 2,
        eccentric: 3,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'ACUTE_WRIST_PAIN'],
      prerequisiteTags: ['PLANK_CONTROL'],
      regressionCodes: ['ELEVATED_PUSH_UP'],
      progressionCodes: ['DUMBBELL_BENCH_PRESS'],
      substitutionCodes: ['ELEVATED_PUSH_UP', 'DUMBBELL_BENCH_PRESS'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'HORIZONTAL_PUSH', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Aseta kädet hieman hartioita leveämmälle.',
        'Pidä vartalo yhtenäisenä.',
        'Laske hallitusti ja työnnä ylös ilman hartioiden kohoamista.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-dumbbell-bench-press-v1',
      code: 'DUMBBELL_BENCH_PRESS',
      version: '1.0.0',
      nameFi: 'Käsipainopenkkipunnerrus',
      method: 'RESISTANCE',
      movementPatterns: ['HORIZONTAL_PUSH'],
      primaryMuscles: ['chest', 'triceps'],
      secondaryMuscles: ['shoulders'],
      equipment: ['Käsipainot'],
      environments: ['GYM', 'HOME'],
      unilateral: false,
      technicalComplexity: 3,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['DUMBBELL_KG_EACH'],
      fatigue: {
        systemic: 2,
        local: 4,
        neural: 2,
        eccentric: 3,
        sorenessRisk: 3,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN'],
      prerequisiteTags: ['SAFE_DUMBBELL_SETUP'],
      regressionCodes: ['ELEVATED_PUSH_UP'],
      progressionCodes: [],
      substitutionCodes: ['ELEVATED_PUSH_UP', 'PUSH_UP'],
      adaptationTargets: [
        'UPPER_BODY_STRENGTH',
        'HORIZONTAL_PUSH',
        'HYPERTROPHY',
        'MAX_STRENGTH',
      ],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-LOAD-001'],
      instructionsFi: [
        'Aseta jalat tukevasti ja lapaluut penkkiä vasten.',
        'Laske painot hallitusti kyynärpäät hieman vartalon alapuolella.',
        'Työnnä painot ylös ilman olkapääkivun provosointia.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-dumbbell-overhead-press-v1',
      code: 'DUMBBELL_OVERHEAD_PRESS',
      version: '1.0.0',
      nameFi: 'Käsipainopystypunnerrus',
      method: 'RESISTANCE',
      movementPatterns: ['VERTICAL_PUSH'],
      primaryMuscles: ['shoulders', 'triceps'],
      secondaryMuscles: ['trunk'],
      equipment: ['Käsipainot'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 3,
      minimumExperience: 'INTERMEDIATE',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['DUMBBELL_KG_EACH'],
      fatigue: {
        systemic: 2,
        local: 3,
        neural: 3,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'OVERHEAD_RESTRICTION'],
      prerequisiteTags: ['PAIN_FREE_OVERHEAD_RANGE'],
      regressionCodes: ['ELEVATED_PUSH_UP'],
      progressionCodes: ['MACHINE_SHOULDER_PRESS'],
      substitutionCodes: ['MACHINE_SHOULDER_PRESS', 'ELEVATED_PUSH_UP'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'VERTICAL_PUSH', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Pidä vartalo vakaana ja kylkiluut hallinnassa.',
        'Työnnä painot ylös kivuttomalla liikeradalla.',
        'Laske painot rauhallisesti takaisin.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-machine-shoulder-press-v1',
      code: 'MACHINE_SHOULDER_PRESS',
      version: '1.0.0',
      nameFi: 'Pystypunnerrus laitteessa',
      method: 'RESISTANCE',
      movementPatterns: ['VERTICAL_PUSH'],
      primaryMuscles: ['shoulders', 'triceps'],
      secondaryMuscles: ['upper chest'],
      equipment: ['Kuntosalilaitteet'],
      environments: ['GYM'],
      unilateral: false,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['MACHINE_KG'],
      fatigue: {
        systemic: 2,
        local: 3,
        neural: 2,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'OVERHEAD_RESTRICTION'],
      prerequisiteTags: ['MACHINE_SETUP', 'PAIN_FREE_OVERHEAD_RANGE'],
      regressionCodes: ['ELEVATED_PUSH_UP'],
      progressionCodes: ['DUMBBELL_OVERHEAD_PRESS'],
      substitutionCodes: ['DUMBBELL_OVERHEAD_PRESS', 'ELEVATED_PUSH_UP'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'VERTICAL_PUSH', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Säädä istuin niin, että kahvat alkavat hartioiden tasolta.',
        'Pidä selkä tuettuna.',
        'Työnnä ja palauta kuorma hallitusti kivuttomalla liikeradalla.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-one-arm-row-v1',
      code: 'ONE_ARM_ROW',
      version: '1.0.0',
      nameFi: 'Yhden käden soutu',
      method: 'RESISTANCE',
      movementPatterns: ['HORIZONTAL_PULL'],
      primaryMuscles: ['latissimus', 'upper back'],
      secondaryMuscles: ['biceps', 'trunk'],
      equipment: ['Käsipainot', 'Kahvakuula'],
      environments: ['HOME', 'GYM'],
      unilateral: true,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['DUMBBELL_KG_EACH', 'EXTERNAL_KG'],
      fatigue: {
        systemic: 2,
        local: 3,
        neural: 2,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'ACUTE_BACK_PAIN'],
      prerequisiteTags: ['SUPPORTED_HINGE'],
      regressionCodes: ['BAND_ROW'],
      progressionCodes: ['SEATED_CABLE_ROW'],
      substitutionCodes: ['SEATED_CABLE_ROW', 'BAND_ROW'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'HORIZONTAL_PULL', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Tue vapaa käsi vakaasti.',
        'Vedä kyynärpää kohti kylkeä ilman vartalon kiertoa.',
        'Palauta paino hallitusti hartiaa nykäisemättä.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-seated-cable-row-v1',
      code: 'SEATED_CABLE_ROW',
      version: '1.0.0',
      nameFi: 'Istumasoutu taljassa',
      method: 'RESISTANCE',
      movementPatterns: ['HORIZONTAL_PULL'],
      primaryMuscles: ['upper back', 'latissimus'],
      secondaryMuscles: ['biceps'],
      equipment: ['Kuntosalilaitteet'],
      environments: ['GYM'],
      unilateral: false,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['MACHINE_KG'],
      fatigue: {
        systemic: 2,
        local: 3,
        neural: 2,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN'],
      prerequisiteTags: ['MACHINE_SETUP'],
      regressionCodes: ['BAND_ROW'],
      progressionCodes: ['ONE_ARM_ROW'],
      substitutionCodes: ['ONE_ARM_ROW', 'BAND_ROW'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'HORIZONTAL_PULL', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Istu ryhdikkäästi ja pidä jalkaterät tuettuina.',
        'Vedä kahva kohti vartaloa ilman taakse keinumista.',
        'Palauta kuorma hallitusti.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-band-row-v1',
      code: 'BAND_ROW',
      version: '1.0.0',
      nameFi: 'Soutu vastuskuminauhalla',
      method: 'RESISTANCE',
      movementPatterns: ['HORIZONTAL_PULL'],
      primaryMuscles: ['upper back', 'latissimus'],
      secondaryMuscles: ['biceps'],
      equipment: ['Vastuskuminauhat'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 1,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BAND'],
      fatigue: {
        systemic: 1,
        local: 2,
        neural: 1,
        eccentric: 1,
        sorenessRisk: 1,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN'],
      prerequisiteTags: ['SAFE_BAND_ANCHOR'],
      regressionCodes: [],
      progressionCodes: ['ONE_ARM_ROW', 'SEATED_CABLE_ROW'],
      substitutionCodes: ['ONE_ARM_ROW', 'SEATED_CABLE_ROW'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'HORIZONTAL_PULL', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Kiinnitä nauha ehjään ja vakaaseen pisteeseen.',
        'Vedä kyynärpäät kohti kylkiä.',
        'Palauta kädet hallitusti ja pidä hartiat rentoina.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-lat-pulldown-v1',
      code: 'LAT_PULLDOWN',
      version: '1.0.0',
      nameFi: 'Ylätalja',
      method: 'RESISTANCE',
      movementPatterns: ['VERTICAL_PULL'],
      primaryMuscles: ['latissimus', 'upper back'],
      secondaryMuscles: ['biceps'],
      equipment: ['Kuntosalilaitteet'],
      environments: ['GYM'],
      unilateral: false,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['MACHINE_KG'],
      fatigue: {
        systemic: 2,
        local: 3,
        neural: 2,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'OVERHEAD_RESTRICTION'],
      prerequisiteTags: ['MACHINE_SETUP', 'PAIN_FREE_OVERHEAD_RANGE'],
      regressionCodes: ['BAND_VERTICAL_PULL'],
      progressionCodes: ['ASSISTED_PULL_UP'],
      substitutionCodes: ['ASSISTED_PULL_UP', 'BAND_VERTICAL_PULL'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'VERTICAL_PULL', 'HYPERTROPHY'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Säädä reisituki ja ota tasainen ote.',
        'Vedä tanko rintakehän yläosaa kohti ilman taakse nojaamista.',
        'Palauta kädet hallitusti ylös.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-assisted-pull-up-v1',
      code: 'ASSISTED_PULL_UP',
      version: '1.0.0',
      nameFi: 'Avustettu leuanveto laitteessa',
      method: 'RESISTANCE',
      movementPatterns: ['VERTICAL_PULL'],
      primaryMuscles: ['latissimus', 'upper back'],
      secondaryMuscles: ['biceps', 'grip'],
      equipment: ['Kuntosalilaitteet'],
      environments: ['GYM'],
      unilateral: false,
      technicalComplexity: 3,
      minimumExperience: 'INTERMEDIATE',
      supervisionRequirement: 'RECOMMENDED',
      minimumAge: 18,
      loadTypes: ['MACHINE_KG'],
      fatigue: {
        systemic: 3,
        local: 4,
        neural: 3,
        eccentric: 3,
        sorenessRisk: 3,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'OVERHEAD_RESTRICTION'],
      prerequisiteTags: ['PAIN_FREE_OVERHEAD_RANGE', 'MACHINE_SETUP'],
      regressionCodes: ['LAT_PULLDOWN', 'BAND_VERTICAL_PULL'],
      progressionCodes: [],
      substitutionCodes: ['LAT_PULLDOWN', 'BAND_VERTICAL_PULL'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'VERTICAL_PULL', 'MAX_STRENGTH'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001', 'CLAIM-ADULT-RT-LOAD-001'],
      instructionsFi: [
        'Säädä avustus niin, että toistot pysyvät hallittuina.',
        'Vedä rintakehää kohti kahvoja hartioita kohauttamatta.',
        'Laskeudu rauhallisesti täyteen hallittuun asentoon.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-band-vertical-pull-v1',
      code: 'BAND_VERTICAL_PULL',
      version: '1.0.0',
      nameFi: 'Pystysuuntainen veto vastuskuminauhalla',
      method: 'RESISTANCE',
      movementPatterns: ['VERTICAL_PULL'],
      primaryMuscles: ['latissimus', 'upper back'],
      secondaryMuscles: ['biceps'],
      equipment: ['Vastuskuminauhat'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BAND'],
      fatigue: {
        systemic: 1,
        local: 2,
        neural: 1,
        eccentric: 1,
        sorenessRisk: 1,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'OVERHEAD_RESTRICTION'],
      prerequisiteTags: ['SAFE_BAND_ANCHOR', 'PAIN_FREE_OVERHEAD_RANGE'],
      regressionCodes: ['BAND_ROW'],
      progressionCodes: ['LAT_PULLDOWN'],
      substitutionCodes: ['LAT_PULLDOWN', 'BAND_ROW'],
      adaptationTargets: ['UPPER_BODY_STRENGTH', 'VERTICAL_PULL', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Kiinnitä nauha varmasti pään yläpuolelle.',
        'Vedä kyynärpäät kohti kylkiä kivuttomalla liikeradalla.',
        'Palauta nauha hitaasti hallintaan.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-standing-calf-raise-v1',
      code: 'STANDING_CALF_RAISE',
      version: '1.0.0',
      nameFi: 'Seisten pohjenousu',
      method: 'RESISTANCE',
      movementPatterns: ['CALF_RAISE'],
      primaryMuscles: ['calves'],
      secondaryMuscles: ['foot stabilizers'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 1,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 1,
        local: 3,
        neural: 1,
        eccentric: 2,
        sorenessRisk: 2,
      },
      contraindicationTags: ['ACHILLES_PAIN', 'CALF_INJURY', 'GAIT_ALTERING_PAIN'],
      prerequisiteTags: ['SUPPORTED_STANCE'],
      regressionCodes: [],
      progressionCodes: [],
      substitutionCodes: ['CHAIR_SQUAT', 'STEP_UP'],
      adaptationTargets: ['CALF_STRENGTH', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Ota kevyt tuki tarvittaessa.',
        'Nouse päkiöille hallitusti.',
        'Laske kantapäät rauhallisesti ilman pomppua.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-dead-bug-v1',
      code: 'DEAD_BUG',
      version: '1.0.0',
      nameFi: 'Dead bug',
      method: 'RESISTANCE',
      movementPatterns: ['ANTI_EXTENSION'],
      primaryMuscles: ['trunk'],
      secondaryMuscles: ['hip flexors'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: true,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 1,
        local: 2,
        neural: 1,
        eccentric: 1,
        sorenessRisk: 1,
      },
      contraindicationTags: ['ACUTE_BACK_PAIN'],
      prerequisiteTags: [],
      regressionCodes: [],
      progressionCodes: ['FRONT_PLANK'],
      substitutionCodes: ['BIRD_DOG', 'FRONT_PLANK'],
      adaptationTargets: ['TRUNK_CONTROL', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Asetu selinmakuulle ja hengitä rauhallisesti.',
        'Ojenna vastakkainen käsi ja jalka ilman selän asennon muuttumista.',
        'Palaa alkuun hallitusti.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-bird-dog-v1',
      code: 'BIRD_DOG',
      version: '1.0.0',
      nameFi: 'Bird dog',
      method: 'RESISTANCE',
      movementPatterns: ['ANTI_ROTATION'],
      primaryMuscles: ['trunk', 'gluteals'],
      secondaryMuscles: ['shoulders'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: true,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 1,
        local: 2,
        neural: 1,
        eccentric: 1,
        sorenessRisk: 1,
      },
      contraindicationTags: ['ACUTE_WRIST_PAIN', 'ACUTE_BACK_PAIN'],
      prerequisiteTags: [],
      regressionCodes: [],
      progressionCodes: ['FRONT_PLANK'],
      substitutionCodes: ['DEAD_BUG', 'FRONT_PLANK'],
      adaptationTargets: ['TRUNK_CONTROL', 'ANTI_ROTATION', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Asetu konttausasentoon.',
        'Ojenna vastakkainen käsi ja jalka ilman lantion kiertoa.',
        'Palaa alkuun hitaasti ja vaihda puolta.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-front-plank-v1',
      code: 'FRONT_PLANK',
      version: '1.0.0',
      nameFi: 'Etulankku',
      method: 'RESISTANCE',
      movementPatterns: ['ANTI_EXTENSION'],
      primaryMuscles: ['trunk'],
      secondaryMuscles: ['shoulders', 'gluteals'],
      equipment: ['Kehonpaino'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BODYWEIGHT'],
      fatigue: {
        systemic: 1,
        local: 3,
        neural: 1,
        eccentric: 1,
        sorenessRisk: 1,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'ACUTE_BACK_PAIN'],
      prerequisiteTags: ['PLANK_CONTROL'],
      regressionCodes: ['DEAD_BUG', 'BIRD_DOG'],
      progressionCodes: ['PALLOF_PRESS'],
      substitutionCodes: ['DEAD_BUG', 'PALLOF_PRESS'],
      adaptationTargets: ['TRUNK_CONTROL', 'ANTI_EXTENSION', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Asetu kyynärvarsien ja varpaiden varaan.',
        'Pidä vartalo suorana ja hengitä rauhallisesti.',
        'Lopeta ennen asennon pettämistä.',
      ],
      status: 'PUBLISHED',
    },
    {
      id: 'exercise-pallof-press-v1',
      code: 'PALLOF_PRESS',
      version: '1.0.0',
      nameFi: 'Pallof-punnerrus',
      method: 'RESISTANCE',
      movementPatterns: ['ANTI_ROTATION'],
      primaryMuscles: ['trunk'],
      secondaryMuscles: ['shoulders', 'gluteals'],
      equipment: ['Vastuskuminauhat', 'Kuntosalilaitteet'],
      environments: ['HOME', 'GYM'],
      unilateral: false,
      technicalComplexity: 2,
      minimumExperience: 'BEGINNER',
      supervisionRequirement: 'NONE',
      minimumAge: 18,
      loadTypes: ['BAND', 'MACHINE_KG'],
      fatigue: {
        systemic: 1,
        local: 2,
        neural: 1,
        eccentric: 1,
        sorenessRisk: 1,
      },
      contraindicationTags: ['ACUTE_SHOULDER_PAIN', 'ACUTE_BACK_PAIN'],
      prerequisiteTags: ['SAFE_BAND_ANCHOR'],
      regressionCodes: ['DEAD_BUG'],
      progressionCodes: [],
      substitutionCodes: ['DEAD_BUG', 'BAND_ROW'],
      adaptationTargets: ['TRUNK_CONTROL', 'ANTI_ROTATION', 'FUNCTION'],
      sportTags: [],
      positionTags: [],
      evidenceClaimIds: ['CLAIM-ADULT-RT-BASE-001'],
      instructionsFi: [
        'Asetu sivuttain vastukseen nähden.',
        'Työnnä kädet eteen vartalon kiertymättä.',
        'Palauta kädet hallitusti rintakehän eteen.',
      ],
      status: 'PUBLISHED',
    },
  ],
  substitutions: [
    {
      fromCode: 'CHAIR_SQUAT',
      toCodes: ['BODYWEIGHT_SQUAT', 'LEG_PRESS'],
    },
    {
      fromCode: 'BODYWEIGHT_SQUAT',
      toCodes: ['CHAIR_SQUAT', 'GOBLET_SQUAT'],
    },
    {
      fromCode: 'GOBLET_SQUAT',
      toCodes: ['BODYWEIGHT_SQUAT', 'LEG_PRESS'],
    },
    {
      fromCode: 'LEG_PRESS',
      toCodes: ['GOBLET_SQUAT', 'CHAIR_SQUAT'],
    },
    {
      fromCode: 'GLUTE_BRIDGE',
      toCodes: ['DUMBBELL_RDL', 'CABLE_PULL_THROUGH'],
    },
    {
      fromCode: 'DUMBBELL_RDL',
      toCodes: ['GLUTE_BRIDGE', 'BARBELL_RDL'],
    },
    {
      fromCode: 'BARBELL_RDL',
      toCodes: ['DUMBBELL_RDL', 'CABLE_PULL_THROUGH'],
    },
    {
      fromCode: 'CABLE_PULL_THROUGH',
      toCodes: ['GLUTE_BRIDGE', 'DUMBBELL_RDL'],
    },
    {
      fromCode: 'SUPPORTED_SPLIT_SQUAT',
      toCodes: ['STEP_UP', 'REVERSE_LUNGE'],
    },
    {
      fromCode: 'REVERSE_LUNGE',
      toCodes: ['SUPPORTED_SPLIT_SQUAT', 'STEP_UP'],
    },
    {
      fromCode: 'STEP_UP',
      toCodes: ['SUPPORTED_SPLIT_SQUAT', 'REVERSE_LUNGE'],
    },
    {
      fromCode: 'ELEVATED_PUSH_UP',
      toCodes: ['PUSH_UP', 'DUMBBELL_BENCH_PRESS'],
    },
    {
      fromCode: 'PUSH_UP',
      toCodes: ['ELEVATED_PUSH_UP', 'DUMBBELL_BENCH_PRESS'],
    },
    {
      fromCode: 'DUMBBELL_BENCH_PRESS',
      toCodes: ['ELEVATED_PUSH_UP', 'PUSH_UP'],
    },
    {
      fromCode: 'DUMBBELL_OVERHEAD_PRESS',
      toCodes: ['MACHINE_SHOULDER_PRESS', 'ELEVATED_PUSH_UP'],
    },
    {
      fromCode: 'MACHINE_SHOULDER_PRESS',
      toCodes: ['DUMBBELL_OVERHEAD_PRESS', 'ELEVATED_PUSH_UP'],
    },
    {
      fromCode: 'ONE_ARM_ROW',
      toCodes: ['SEATED_CABLE_ROW', 'BAND_ROW'],
    },
    {
      fromCode: 'SEATED_CABLE_ROW',
      toCodes: ['ONE_ARM_ROW', 'BAND_ROW'],
    },
    {
      fromCode: 'BAND_ROW',
      toCodes: ['ONE_ARM_ROW', 'SEATED_CABLE_ROW'],
    },
    {
      fromCode: 'LAT_PULLDOWN',
      toCodes: ['ASSISTED_PULL_UP', 'BAND_VERTICAL_PULL'],
    },
    {
      fromCode: 'ASSISTED_PULL_UP',
      toCodes: ['LAT_PULLDOWN', 'BAND_VERTICAL_PULL'],
    },
    {
      fromCode: 'BAND_VERTICAL_PULL',
      toCodes: ['LAT_PULLDOWN', 'BAND_ROW'],
    },
    {
      fromCode: 'STANDING_CALF_RAISE',
      toCodes: ['CHAIR_SQUAT', 'STEP_UP'],
    },
    {
      fromCode: 'DEAD_BUG',
      toCodes: ['BIRD_DOG', 'FRONT_PLANK'],
    },
    {
      fromCode: 'BIRD_DOG',
      toCodes: ['DEAD_BUG', 'FRONT_PLANK'],
    },
    {
      fromCode: 'FRONT_PLANK',
      toCodes: ['DEAD_BUG', 'PALLOF_PRESS'],
    },
    {
      fromCode: 'PALLOF_PRESS',
      toCodes: ['DEAD_BUG', 'BAND_ROW'],
    },
  ],
} as const
